import { useState, useEffect, useCallback, useRef } from "react";
import MapViewer from "@/components/MapViewer";
import type { MapViewerHandle } from "@/components/MapViewer";
import ChatPanel from "@/components/ChatPanel";
import InsightsPanel from "@/components/InsightsPanel";
import LayerControls from "@/components/LayerControls";
import QuickOSM from "@/components/QuickOSM";
import { Button } from "@/components/ui/button";
import { Download, CheckCircle, ChevronDown, Search, Loader2, X, Camera } from "lucide-react";

interface CustomOverlay {
  id: string;
  label: string;
  color: string;
  data: any;
}

export default function Home() {
  const mapRef = useRef<MapViewerHandle>(null);
  const [arcgisApiKey, setArcgisApiKey] = useState("");
  const [activeLayers, setActiveLayers] = useState<string[]>([]);
  const [loadingLayers, setLoadingLayers] = useState<string[]>([]);
  const [leftTab, setLeftTab] = useState<"layers" | "chat" | "query">("layers");
  const [selectedLocation, setSelectedLocation] = useState<{lat: number, lon: number, name: string}>({
    lat: 37.7749,
    lon: -122.4194,
    name: "San Francisco, CA"
  });
  const [searchQuery, setSearchQuery] = useState("");
  const [searchResults, setSearchResults] = useState<any[]>([]);
  const [isSearching, setIsSearching] = useState(false);
  const [analysisReady, setAnalysisReady] = useState(false);
  const [customOverlays, setCustomOverlays] = useState<CustomOverlay[]>([]);

  useEffect(() => {
    fetch("/api/config")
      .then(res => res.json())
      .then(data => setArcgisApiKey(data.arcgisApiKey || ""))
      .catch(() => {});
  }, []);

  const handleLocationSelect = useCallback((lat: number, lon: number, name: string) => {
    setSelectedLocation({ lat, lon, name });
    setAnalysisReady(false);
  }, []);

  const handleToggleLayer = useCallback((id: string) => {
    setActiveLayers(prev =>
      prev.includes(id) ? prev.filter(l => l !== id) : [...prev, id]
    );
  }, []);

  const handleLayerLoading = useCallback((layerId: string, loading: boolean) => {
    setLoadingLayers(prev =>
      loading ? [...prev.filter(l => l !== layerId), layerId] : prev.filter(l => l !== layerId)
    );
  }, []);

  const handleCustomDataLoaded = useCallback((data: any, label: string, color: string) => {
    const id = `custom-${Date.now()}`;
    setCustomOverlays(prev => [...prev, { id, label, color, data }]);
  }, []);

  const removeCustomOverlay = useCallback((id: string) => {
    setCustomOverlays(prev => prev.filter(o => o.id !== id));
  }, []);

  const handleSearch = async () => {
    if (!searchQuery.trim()) return;
    setIsSearching(true);
    try {
      const response = await fetch(`/api/geocode?q=${encodeURIComponent(searchQuery)}`);
      const data = await response.json();
      setSearchResults(data || []);
    } catch {
      setSearchResults([]);
    } finally {
      setIsSearching(false);
    }
  };

  const selectSearchResult = (result: any) => {
    const { x, y } = result.location;
    handleLocationSelect(y, x, result.address);
    setSearchResults([]);
    setSearchQuery(result.address);
  };

  const loadCaseStudy = () => {
    handleLocationSelect(17.3850, 78.4867, "Hyderabad, India");
    setSearchQuery("Hyderabad, India");
  };

  const exportReport = () => {
    if (!selectedLocation) return;
    fetch("/api/analyze", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ lat: selectedLocation.lat, lon: selectedLocation.lon, name: selectedLocation.name }),
    })
      .then(r => r.json())
      .then(analysis => {
        const report = `TerraLogic AI - Site Analysis Report
==========================================
Location: ${selectedLocation.name}
Coordinates: ${selectedLocation.lat.toFixed(6)}, ${selectedLocation.lon.toFixed(6)}
Date: ${new Date().toLocaleDateString()}

Overall Suitability: ${analysis.overallScore}/100 (${analysis.rating})

Site Information:
- Elevation: ${analysis.siteInfo?.elevation || 'N/A'} ${analysis.siteInfo?.elevationUnit || 'm ASL'}
- Zoning: ${analysis.siteInfo?.zoning || 'N/A'}

Environmental Metrics:
- Sun Exposure: ${analysis.environmentalMetrics?.sunExposure || 'N/A'}%
- Soil Quality: ${analysis.environmentalMetrics?.soilQuality || 'N/A'}%
- Wind Exposure: ${analysis.environmentalMetrics?.windExposure || 'N/A'}%
- Flood Risk: ${analysis.environmentalMetrics?.floodRisk || 'N/A'}

Factors:
${analysis.factors?.map((f: any) => `- ${f.name}: ${f.value}% (${f.category})`).join('\n') || 'N/A'}

Nearby Amenities:
- Schools: ${analysis.amenities?.schools || 0}
- Transit Stops: ${analysis.amenities?.transitStops || 0}
- Hospitals: ${analysis.amenities?.hospitals || 0}
- Parks: ${analysis.amenities?.parks || 0}

Recommendations:
${analysis.recommendations?.map((r: any) => `[${r.type.toUpperCase()}] ${r.title}: ${r.description}`).join('\n') || 'N/A'}

Generated by TerraLogic AI - GIS Spatial Analysis Platform`;

        const blob = new Blob([report], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `TerraLogic_Report_${selectedLocation.name.replace(/[^a-zA-Z0-9]/g, '_')}.txt`;
        a.click();
        URL.revokeObjectURL(url);
      })
      .catch(() => {});
  };

  return (
    <div className="flex h-screen w-full bg-background overflow-hidden flex-col">
      <header className="h-12 border-b border-border bg-card flex items-center px-4 justify-between z-10 shrink-0">
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-md bg-primary/15 border border-primary/30 flex items-center justify-center" data-testid="logo">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-primary">
                <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20" /><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z" />
              </svg>
            </div>
            <span className="font-semibold text-sm text-foreground tracking-tight">TerraLogic AI</span>
          </div>

          <div className="hidden md:flex items-center gap-1 ml-2 px-3 py-1.5 bg-muted/60 rounded-md border border-border cursor-default" data-testid="project-selector">
            <span className="text-xs text-muted-foreground truncate max-w-[200px]">
              {selectedLocation.name || "Select Location"}
            </span>
            <ChevronDown className="w-3 h-3 text-muted-foreground" />
          </div>
        </div>

        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={loadCaseStudy}
            className="border-primary/40 text-primary hover:bg-primary/10 text-xs h-7 px-3"
            data-testid="button-case-study"
          >
            <CheckCircle className="w-3 h-3 mr-1" />
            <span className="hidden sm:inline">Hyderabad Case Study</span>
            <span className="sm:hidden">Case Study</span>
          </Button>
          <Button
            size="sm"
            onClick={() => mapRef.current?.exportMapAsPNG()}
            className="border-primary/40 text-primary hover:bg-primary/10 text-xs h-7 px-3"
            variant="outline"
            data-testid="button-export-map"
          >
            <Camera className="w-3 h-3 mr-1" />
            Export Map
          </Button>
          <Button
            size="sm"
            onClick={exportReport}
            className="bg-primary hover:bg-primary/90 text-primary-foreground text-xs h-7 px-3"
            data-testid="button-export"
          >
            <Download className="w-3 h-3 mr-1" />
            Export Report
          </Button>
        </div>
      </header>

      <div className="flex-1 flex overflow-hidden">
        <div className="w-[300px] min-w-[260px] border-r border-border bg-card flex flex-col shrink-0">
          <div className="p-4 pb-3">
            <h2 className="font-semibold text-sm text-foreground" data-testid="text-project-overview">Project Overview</h2>
            <p className="text-[11px] text-muted-foreground mt-0.5">Urban analysis & site intelligence</p>
          </div>

          <div className="px-4 pb-3">
            <label className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider mb-1.5 block">Search Location</label>
            <div className="flex gap-1.5">
              <div className="relative flex-1">
                <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-muted-foreground" />
                <input
                  type="text"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && handleSearch()}
                  placeholder="City, address, or coordinates..."
                  className="w-full bg-input border border-border rounded-md px-3 pl-8 py-2 text-xs text-foreground placeholder:text-muted-foreground/60 focus:outline-none focus:ring-1 focus:ring-primary/50"
                  data-testid="input-search-location"
                />
              </div>
              <Button
                size="sm"
                onClick={handleSearch}
                disabled={!searchQuery.trim() || isSearching}
                className="h-[34px] w-[34px] p-0 bg-primary hover:bg-primary/90"
                data-testid="button-search"
              >
                {isSearching ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Search className="w-3.5 h-3.5" />}
              </Button>
            </div>
            {searchResults.length > 0 && (
              <div className="mt-1 bg-card border border-border rounded-md shadow-lg overflow-hidden max-h-[180px] overflow-y-auto">
                {searchResults.map((r, i) => (
                  <div
                    key={i}
                    onClick={() => selectSearchResult(r)}
                    className="px-3 py-2 text-xs text-foreground hover:bg-muted/60 cursor-pointer border-b border-border/50 last:border-0"
                    data-testid={`search-result-${i}`}
                  >
                    {r.address}
                  </div>
                ))}
              </div>
            )}
          </div>

          <div className="px-4 pb-2 flex gap-1">
            <button
              onClick={() => setLeftTab("layers")}
              className={`flex items-center gap-1 px-2 py-1.5 rounded-md text-[11px] font-medium transition-colors ${
                leftTab === "layers"
                  ? "bg-primary text-primary-foreground"
                  : "text-muted-foreground hover:text-foreground hover:bg-muted/40"
              }`}
              data-testid="button-tab-layers"
            >
              <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="m12 2 10 6.5v7L12 22 2 15.5v-7L12 2z"/><path d="M12 22V15.5"/><path d="m22 8.5-10 7-10-7"/></svg>
              Layers
            </button>
            <button
              onClick={() => setLeftTab("query")}
              className={`flex items-center gap-1 px-2 py-1.5 rounded-md text-[11px] font-medium transition-colors ${
                leftTab === "query"
                  ? "bg-primary text-primary-foreground"
                  : "text-muted-foreground hover:text-foreground hover:bg-muted/40"
              }`}
              data-testid="button-tab-query"
            >
              <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/></svg>
              QuickOSM
            </button>
            <button
              onClick={() => setLeftTab("chat")}
              className={`flex items-center gap-1 px-2 py-1.5 rounded-md text-[11px] font-medium transition-colors ${
                leftTab === "chat"
                  ? "bg-primary text-primary-foreground"
                  : "text-muted-foreground hover:text-foreground hover:bg-muted/40"
              }`}
              data-testid="button-tab-chat"
            >
              <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 8V4H8"/><rect width="16" height="12" x="4" y="8" rx="2"/><path d="m2 14 6-6 6 6"/></svg>
              AI
            </button>
          </div>

          <div className="flex-1 overflow-hidden flex flex-col min-h-0">
            {leftTab === "layers" ? (
              <LayerControls
                activeLayers={activeLayers}
                onToggleLayer={handleToggleLayer}
                loadingLayers={loadingLayers}
              />
            ) : leftTab === "query" ? (
              <QuickOSM location={selectedLocation} onDataLoaded={handleCustomDataLoaded} />
            ) : (
              <ChatPanel location={selectedLocation} onToggleLayer={handleToggleLayer} activeLayers={activeLayers} />
            )}
          </div>

          {customOverlays.length > 0 && (
            <div className="px-3 py-2 border-t border-border">
              <p className="text-[10px] uppercase tracking-wider font-semibold text-muted-foreground mb-1">Custom Overlays</p>
              <div className="space-y-0.5 max-h-[80px] overflow-y-auto">
                {customOverlays.map((overlay) => (
                  <div key={overlay.id} className="flex items-center gap-2 text-[11px]">
                    <div className="w-2 h-2 rounded-full shrink-0" style={{ background: overlay.color }} />
                    <span className="truncate flex-1 text-foreground">{overlay.label}</span>
                    <span className="text-muted-foreground text-[10px]">{overlay.data?.features?.length || 0}</span>
                    <button onClick={() => removeCustomOverlay(overlay.id)} className="text-muted-foreground hover:text-foreground shrink-0">
                      <X className="w-3 h-3" />
                    </button>
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className="px-4 py-2.5 border-t border-border flex items-center justify-between text-[11px] text-muted-foreground">
            <span>Active Layers <strong className="text-foreground">{activeLayers.length + customOverlays.length}/{10 + customOverlays.length}</strong></span>
            <span className="flex items-center gap-1">
              Analysis Ready
              {analysisReady ? (
                <CheckCircle className="w-3 h-3 text-primary" />
              ) : (
                <span className="w-3 h-3 rounded-full border border-muted-foreground/40 inline-block" />
              )}
            </span>
          </div>
        </div>

        <div className="flex-1 relative z-0">
          <MapViewer
            ref={mapRef}
            onLocationSelect={handleLocationSelect}
            arcgisApiKey={arcgisApiKey}
            activeLayers={activeLayers}
            onLayerLoading={handleLayerLoading}
            selectedLocation={selectedLocation}
            customOverlays={customOverlays}
          />
        </div>

        <div className="w-[320px] min-w-[280px] border-l border-border bg-card overflow-hidden shrink-0">
          <InsightsPanel location={selectedLocation} onAnalysisReady={() => setAnalysisReady(true)} />
        </div>
      </div>
    </div>
  );
}
